"""add_email_enabled_to_notification_preferences

Revision ID: 339885d7f6fa
Revises: 369d67886082
Create Date: 2025-12-18 20:18:24.633497

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "339885d7f6fa"
down_revision: str | Sequence[str] | None = "369d67886082"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default True for existing rows
    op.add_column(
        "notification_preferences",
        sa.Column("email_enabled", sa.Boolean(), nullable=False, server_default="true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification_preferences", "email_enabled")
    # ### end Alembic commands ###
