"""add_export_history

Revision ID: 36cdf62d465b
Revises: a054d78f2aa5
Create Date: 2025-12-19 10:51:59.341750

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "36cdf62d465b"
down_revision: str | Sequence[str] | None = "a054d78f2aa5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("export_type", sa.String(length=30), nullable=False),
        sa.Column("export_format", sa.String(length=10), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("record_count", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=50), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("extra_data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_export_history_export_type"), "export_history", ["export_type"], unique=False
    )
    op.create_index(op.f("ix_export_history_user_id"), "export_history", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_export_history_user_id"), table_name="export_history")
    op.drop_index(op.f("ix_export_history_export_type"), table_name="export_history")
    op.drop_table("export_history")
    # ### end Alembic commands ###
