"""add_icon_cache_and_ai_preferences

Revision ID: 55688a8830bc
Revises: 36cdf62d465b
Create Date: 2025-12-19 17:38:41.189590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55688a8830bc'
down_revision: Union[str, Sequence[str], None] = '36cdf62d465b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False, comment='Whether AI assistant is enabled'),
    sa.Column('preferred_model', sa.Enum('HAIKU', 'SONNET', 'OPUS', name='aimodel'), nullable=False, comment='Preferred AI model'),
    sa.Column('auto_categorization', sa.Boolean(), nullable=False, comment='Auto-categorize new subscriptions'),
    sa.Column('auto_icon_assignment', sa.Boolean(), nullable=False, comment='Auto-assign icons to subscriptions'),
    sa.Column('smart_suggestions', sa.Boolean(), nullable=False, comment='Enable smart suggestions'),
    sa.Column('suggestion_frequency', sa.Enum('OFF', 'MINIMAL', 'NORMAL', 'PROACTIVE', name='suggestionfrequency'), nullable=False, comment='How often to show suggestions'),
    sa.Column('confidence_threshold', sa.Float(), nullable=False, comment='Minimum confidence for auto-actions (0.0-1.0)'),
    sa.Column('icon_generation_enabled', sa.Boolean(), nullable=False, comment='Allow AI to generate icons'),
    sa.Column('icon_style', sa.Enum('MINIMAL', 'BRANDED', 'PLAYFUL', 'CORPORATE', name='icongenerationstyle'), nullable=False, comment='Style for AI-generated icons'),
    sa.Column('icon_size', sa.Integer(), nullable=False, comment='Preferred icon size in pixels'),
    sa.Column('conversation_history_enabled', sa.Boolean(), nullable=False, comment='Save conversation history'),
    sa.Column('conversation_history_days', sa.Integer(), nullable=False, comment='Days to keep conversation history'),
    sa.Column('natural_language_parsing', sa.Boolean(), nullable=False, comment='Enable natural language command parsing'),
    sa.Column('learn_from_corrections', sa.Boolean(), nullable=False, comment='Learn from user corrections'),
    sa.Column('privacy_mode', sa.Boolean(), nullable=False, comment='Minimize data sent to AI'),
    sa.Column('custom_instructions', sa.Text(), nullable=True, comment='Custom instructions for AI assistant'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_preferences_user_id'), 'ai_preferences', ['user_id'], unique=True)
    op.create_table('icon_cache',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False, comment='Normalized service name (lowercase)'),
    sa.Column('display_name', sa.String(length=200), nullable=True, comment='Human-readable service name'),
    sa.Column('source', sa.Enum('SIMPLE_ICONS', 'CLEARBIT', 'LOGO_DEV', 'BRANDFETCH', 'AI_GENERATED', 'USER_UPLOADED', 'FALLBACK', name='iconsource'), nullable=False),
    sa.Column('icon_url', sa.String(length=1000), nullable=True, comment='URL to the icon'),
    sa.Column('icon_data', sa.Text(), nullable=True, comment='Base64 encoded icon data'),
    sa.Column('brand_color', sa.String(length=7), nullable=True, comment='Primary brand color (hex)'),
    sa.Column('secondary_color', sa.String(length=7), nullable=True, comment='Secondary brand color (hex)'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Service category'),
    sa.Column('width', sa.Integer(), nullable=True, comment='Icon width in pixels'),
    sa.Column('height', sa.Integer(), nullable=True, comment='Icon height in pixels'),
    sa.Column('format', sa.String(length=10), nullable=True, comment='Image format (svg, png, webp)'),
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Owner user ID (null for global cache)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='When the cache entry expires'),
    sa.Column('fetch_count', sa.Integer(), nullable=False, comment='Number of times this icon was fetched'),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='When the icon was last fetched'),
    sa.Column('is_verified', sa.Boolean(), nullable=False, comment='Whether the icon was verified by admin'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icon_cache_expires_at'), 'icon_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_icon_cache_service_name'), 'icon_cache', ['service_name'], unique=False)
    op.create_index('ix_icon_cache_service_user', 'icon_cache', ['service_name', 'user_id'], unique=True)
    op.create_index('ix_icon_cache_source_expires', 'icon_cache', ['source', 'expires_at'], unique=False)
    op.create_index(op.f('ix_icon_cache_user_id'), 'icon_cache', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_icon_cache_user_id'), table_name='icon_cache')
    op.drop_index('ix_icon_cache_source_expires', table_name='icon_cache')
    op.drop_index('ix_icon_cache_service_user', table_name='icon_cache')
    op.drop_index(op.f('ix_icon_cache_service_name'), table_name='icon_cache')
    op.drop_index(op.f('ix_icon_cache_expires_at'), table_name='icon_cache')
    op.drop_table('icon_cache')
    op.drop_index(op.f('ix_ai_preferences_user_id'), table_name='ai_preferences')
    op.drop_table('ai_preferences')

    # Drop enum types
    sa.Enum(name='iconsource').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='icongenerationstyle').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='suggestionfrequency').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='aimodel').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
