"""add_statement_import_tables

Revision ID: 69107cd3b0ea
Revises: 0a1c54d55e2f
Create Date: 2025-12-20 13:44:48.048913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69107cd3b0ea'
down_revision: Union[str, Sequence[str], None] = '0a1c54d55e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
