"""add_funding_card_id_to_payment_cards

Revision ID: 8288763654e3
Revises: g2b3c4d5e678
Create Date: 2025-12-07 17:42:08.700695

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8288763654e3"
down_revision: str | Sequence[str] | None = "g2b3c4d5e678"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "payment_cards", sa.Column("funding_card_id", sa.String(length=36), nullable=True)
    )
    op.create_foreign_key(None, "payment_cards", "payment_cards", ["funding_card_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "payment_cards", type_="foreignkey")
    op.drop_column("payment_cards", "funding_card_id")
    # ### end Alembic commands ###
