"""add_push_notification_fields

Revision ID: 9377d33097e1
Revises: 339885d7f6fa
Create Date: 2025-12-19 10:31:27.759438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9377d33097e1'
down_revision: Union[str, Sequence[str], None] = '339885d7f6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notification_preferences',
        sa.Column('push_enabled', sa.Boolean(), nullable=False, server_default='false')
    )
    op.add_column(
        'notification_preferences',
        sa.Column('push_subscription', sa.String(length=2000), nullable=True)
    )
    op.add_column(
        'notification_preferences',
        sa.Column('push_verified', sa.Boolean(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'push_verified')
    op.drop_column('notification_preferences', 'push_subscription')
    op.drop_column('notification_preferences', 'push_enabled')
    # ### end Alembic commands ###
