"""add_scheduled_report_settings

Revision ID: a054d78f2aa5
Revises: d251356550ca
Create Date: 2025-12-19 10:50:24.235014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a054d78f2aa5'
down_revision: Union[str, Sequence[str], None] = 'd251356550ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'notification_preferences',
        sa.Column('report_enabled', sa.Boolean(), nullable=False, server_default='false')
    )
    op.add_column(
        'notification_preferences',
        sa.Column('report_frequency', sa.String(length=20), nullable=False, server_default='weekly')
    )
    op.add_column(
        'notification_preferences',
        sa.Column('report_day', sa.Integer(), nullable=False, server_default='0')
    )
    op.add_column(
        'notification_preferences',
        sa.Column('report_time', sa.Time(), nullable=False, server_default='08:00:00')
    )
    op.add_column(
        'notification_preferences',
        sa.Column('report_include_charts', sa.Boolean(), nullable=False, server_default='true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_preferences', 'report_include_charts')
    op.drop_column('notification_preferences', 'report_time')
    op.drop_column('notification_preferences', 'report_day')
    op.drop_column('notification_preferences', 'report_frequency')
    op.drop_column('notification_preferences', 'report_enabled')
    # ### end Alembic commands ###
