"""add_notification_history

Revision ID: d251356550ca
Revises: 9377d33097e1
Create Date: 2025-12-19 10:45:37.313721

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d251356550ca"
down_revision: str | Sequence[str] | None = "9377d33097e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("subscription_id", sa.String(length=36), nullable=True),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("notification_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("delivered_at", sa.DateTime(), nullable=True),
        sa.Column("extra_data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_history_channel"), "notification_history", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_notification_history_notification_type"),
        "notification_history",
        ["notification_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_history_user_id"), "notification_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_notification_history_user_id"), table_name="notification_history")
    op.drop_index(
        op.f("ix_notification_history_notification_type"), table_name="notification_history"
    )
    op.drop_index(op.f("ix_notification_history_channel"), table_name="notification_history")
    op.drop_table("notification_history")
    # ### end Alembic commands ###
